version: "3.2"
services:
  api:
    image: flask_api
    container_name: ml_api
    build:
      context: ./api
    command: "gunicorn --workers=8 --bind 0.0.0.0:5000 app:app"
    ports:
      - "80:5000"
    environment:
      - FLASK_DEBUG=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_QUEUE=service_queue
      - REDIS_QUEUE_FEEDBACK=feedback_queue
    depends_on:
      - redis
      - model
      - feedback
    tty: true
    logging:
      driver: "gelf"
      options:
        gelf-address: "udp://localhost:12201"
        tag: "api-logs"

  redis:
    image: redis:5.0.6

  model:
    image: ml_service
    container_name: ml_service
    build:
      context: ./model
    command: "python3 /src/ml_service.py"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_QUEUE=service_queue
    depends_on:
      - redis

  feedback:
    image: ml_feedback
    container_name: ml_feedback
    build:
      context: ./feedback
    command: "python3 /src/ml_feedback.py"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
      - REDIS_QUEUE_FEEDBACK=feedback_queue
    volumes:
      - ./data:/data/
    depends_on:
      - redis